# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = "/Applications/CMake 2.8-12.app/Contents/bin/cmake"

# The command to remove a file.
RM = "/Applications/CMake 2.8-12.app/Contents/bin/cmake" -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = "/Applications/CMake 2.8-12.app/Contents/bin/ccmake"

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/jar/hack/osxinj_tut

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/jar/hack/osxinj_tut

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	"/Applications/CMake 2.8-12.app/Contents/bin/ccmake" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"/Applications/CMake 2.8-12.app/Contents/bin/cmake" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/jar/hack/osxinj_tut/CMakeFiles /Users/jar/hack/osxinj_tut/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/jar/hack/osxinj_tut/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named bootstrap

# Build rule for target.
bootstrap: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bootstrap
.PHONY : bootstrap

# fast build rule for target.
bootstrap/fast:
	$(MAKE) -f CMakeFiles/bootstrap.dir/build.make CMakeFiles/bootstrap.dir/build
.PHONY : bootstrap/fast

#=============================================================================
# Target rules for targets named osxinj

# Build rule for target.
osxinj: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osxinj
.PHONY : osxinj

# fast build rule for target.
osxinj/fast:
	$(MAKE) -f CMakeFiles/osxinj.dir/build.make CMakeFiles/osxinj.dir/build
.PHONY : osxinj/fast

#=============================================================================
# Target rules for targets named testapp

# Build rule for target.
testapp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 testapp
.PHONY : testapp

# fast build rule for target.
testapp/fast:
	$(MAKE) -f CMakeFiles/testapp.dir/build.make CMakeFiles/testapp.dir/build
.PHONY : testapp/fast

#=============================================================================
# Target rules for targets named testdylib

# Build rule for target.
testdylib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 testdylib
.PHONY : testdylib

# fast build rule for target.
testdylib/fast:
	$(MAKE) -f CMakeFiles/testdylib.dir/build.make CMakeFiles/testdylib.dir/build
.PHONY : testdylib/fast

src/bootstrap/main.o: src/bootstrap/main.cpp.o
.PHONY : src/bootstrap/main.o

# target to build an object file
src/bootstrap/main.cpp.o:
	$(MAKE) -f CMakeFiles/bootstrap.dir/build.make CMakeFiles/bootstrap.dir/src/bootstrap/main.cpp.o
.PHONY : src/bootstrap/main.cpp.o

src/bootstrap/main.i: src/bootstrap/main.cpp.i
.PHONY : src/bootstrap/main.i

# target to preprocess a source file
src/bootstrap/main.cpp.i:
	$(MAKE) -f CMakeFiles/bootstrap.dir/build.make CMakeFiles/bootstrap.dir/src/bootstrap/main.cpp.i
.PHONY : src/bootstrap/main.cpp.i

src/bootstrap/main.s: src/bootstrap/main.cpp.s
.PHONY : src/bootstrap/main.s

# target to generate assembly for a file
src/bootstrap/main.cpp.s:
	$(MAKE) -f CMakeFiles/bootstrap.dir/build.make CMakeFiles/bootstrap.dir/src/bootstrap/main.cpp.s
.PHONY : src/bootstrap/main.cpp.s

src/osxinj/injector.o: src/osxinj/injector.cpp.o
.PHONY : src/osxinj/injector.o

# target to build an object file
src/osxinj/injector.cpp.o:
	$(MAKE) -f CMakeFiles/osxinj.dir/build.make CMakeFiles/osxinj.dir/src/osxinj/injector.cpp.o
.PHONY : src/osxinj/injector.cpp.o

src/osxinj/injector.i: src/osxinj/injector.cpp.i
.PHONY : src/osxinj/injector.i

# target to preprocess a source file
src/osxinj/injector.cpp.i:
	$(MAKE) -f CMakeFiles/osxinj.dir/build.make CMakeFiles/osxinj.dir/src/osxinj/injector.cpp.i
.PHONY : src/osxinj/injector.cpp.i

src/osxinj/injector.s: src/osxinj/injector.cpp.s
.PHONY : src/osxinj/injector.s

# target to generate assembly for a file
src/osxinj/injector.cpp.s:
	$(MAKE) -f CMakeFiles/osxinj.dir/build.make CMakeFiles/osxinj.dir/src/osxinj/injector.cpp.s
.PHONY : src/osxinj/injector.cpp.s

src/osxinj/mach_inject.o: src/osxinj/mach_inject.c.o
.PHONY : src/osxinj/mach_inject.o

# target to build an object file
src/osxinj/mach_inject.c.o:
	$(MAKE) -f CMakeFiles/osxinj.dir/build.make CMakeFiles/osxinj.dir/src/osxinj/mach_inject.c.o
.PHONY : src/osxinj/mach_inject.c.o

src/osxinj/mach_inject.i: src/osxinj/mach_inject.c.i
.PHONY : src/osxinj/mach_inject.i

# target to preprocess a source file
src/osxinj/mach_inject.c.i:
	$(MAKE) -f CMakeFiles/osxinj.dir/build.make CMakeFiles/osxinj.dir/src/osxinj/mach_inject.c.i
.PHONY : src/osxinj/mach_inject.c.i

src/osxinj/mach_inject.s: src/osxinj/mach_inject.c.s
.PHONY : src/osxinj/mach_inject.s

# target to generate assembly for a file
src/osxinj/mach_inject.c.s:
	$(MAKE) -f CMakeFiles/osxinj.dir/build.make CMakeFiles/osxinj.dir/src/osxinj/mach_inject.c.s
.PHONY : src/osxinj/mach_inject.c.s

src/osxinj/main.o: src/osxinj/main.cpp.o
.PHONY : src/osxinj/main.o

# target to build an object file
src/osxinj/main.cpp.o:
	$(MAKE) -f CMakeFiles/osxinj.dir/build.make CMakeFiles/osxinj.dir/src/osxinj/main.cpp.o
.PHONY : src/osxinj/main.cpp.o

src/osxinj/main.i: src/osxinj/main.cpp.i
.PHONY : src/osxinj/main.i

# target to preprocess a source file
src/osxinj/main.cpp.i:
	$(MAKE) -f CMakeFiles/osxinj.dir/build.make CMakeFiles/osxinj.dir/src/osxinj/main.cpp.i
.PHONY : src/osxinj/main.cpp.i

src/osxinj/main.s: src/osxinj/main.cpp.s
.PHONY : src/osxinj/main.s

# target to generate assembly for a file
src/osxinj/main.cpp.s:
	$(MAKE) -f CMakeFiles/osxinj.dir/build.make CMakeFiles/osxinj.dir/src/osxinj/main.cpp.s
.PHONY : src/osxinj/main.cpp.s

src/testapp/main.o: src/testapp/main.cpp.o
.PHONY : src/testapp/main.o

# target to build an object file
src/testapp/main.cpp.o:
	$(MAKE) -f CMakeFiles/testapp.dir/build.make CMakeFiles/testapp.dir/src/testapp/main.cpp.o
.PHONY : src/testapp/main.cpp.o

src/testapp/main.i: src/testapp/main.cpp.i
.PHONY : src/testapp/main.i

# target to preprocess a source file
src/testapp/main.cpp.i:
	$(MAKE) -f CMakeFiles/testapp.dir/build.make CMakeFiles/testapp.dir/src/testapp/main.cpp.i
.PHONY : src/testapp/main.cpp.i

src/testapp/main.s: src/testapp/main.cpp.s
.PHONY : src/testapp/main.s

# target to generate assembly for a file
src/testapp/main.cpp.s:
	$(MAKE) -f CMakeFiles/testapp.dir/build.make CMakeFiles/testapp.dir/src/testapp/main.cpp.s
.PHONY : src/testapp/main.cpp.s

src/testdylib/libudis86/decode.o: src/testdylib/libudis86/decode.c.o
.PHONY : src/testdylib/libudis86/decode.o

# target to build an object file
src/testdylib/libudis86/decode.c.o:
	$(MAKE) -f CMakeFiles/testdylib.dir/build.make CMakeFiles/testdylib.dir/src/testdylib/libudis86/decode.c.o
.PHONY : src/testdylib/libudis86/decode.c.o

src/testdylib/libudis86/decode.i: src/testdylib/libudis86/decode.c.i
.PHONY : src/testdylib/libudis86/decode.i

# target to preprocess a source file
src/testdylib/libudis86/decode.c.i:
	$(MAKE) -f CMakeFiles/testdylib.dir/build.make CMakeFiles/testdylib.dir/src/testdylib/libudis86/decode.c.i
.PHONY : src/testdylib/libudis86/decode.c.i

src/testdylib/libudis86/decode.s: src/testdylib/libudis86/decode.c.s
.PHONY : src/testdylib/libudis86/decode.s

# target to generate assembly for a file
src/testdylib/libudis86/decode.c.s:
	$(MAKE) -f CMakeFiles/testdylib.dir/build.make CMakeFiles/testdylib.dir/src/testdylib/libudis86/decode.c.s
.PHONY : src/testdylib/libudis86/decode.c.s

src/testdylib/libudis86/input.o: src/testdylib/libudis86/input.c.o
.PHONY : src/testdylib/libudis86/input.o

# target to build an object file
src/testdylib/libudis86/input.c.o:
	$(MAKE) -f CMakeFiles/testdylib.dir/build.make CMakeFiles/testdylib.dir/src/testdylib/libudis86/input.c.o
.PHONY : src/testdylib/libudis86/input.c.o

src/testdylib/libudis86/input.i: src/testdylib/libudis86/input.c.i
.PHONY : src/testdylib/libudis86/input.i

# target to preprocess a source file
src/testdylib/libudis86/input.c.i:
	$(MAKE) -f CMakeFiles/testdylib.dir/build.make CMakeFiles/testdylib.dir/src/testdylib/libudis86/input.c.i
.PHONY : src/testdylib/libudis86/input.c.i

src/testdylib/libudis86/input.s: src/testdylib/libudis86/input.c.s
.PHONY : src/testdylib/libudis86/input.s

# target to generate assembly for a file
src/testdylib/libudis86/input.c.s:
	$(MAKE) -f CMakeFiles/testdylib.dir/build.make CMakeFiles/testdylib.dir/src/testdylib/libudis86/input.c.s
.PHONY : src/testdylib/libudis86/input.c.s

src/testdylib/libudis86/itab.o: src/testdylib/libudis86/itab.c.o
.PHONY : src/testdylib/libudis86/itab.o

# target to build an object file
src/testdylib/libudis86/itab.c.o:
	$(MAKE) -f CMakeFiles/testdylib.dir/build.make CMakeFiles/testdylib.dir/src/testdylib/libudis86/itab.c.o
.PHONY : src/testdylib/libudis86/itab.c.o

src/testdylib/libudis86/itab.i: src/testdylib/libudis86/itab.c.i
.PHONY : src/testdylib/libudis86/itab.i

# target to preprocess a source file
src/testdylib/libudis86/itab.c.i:
	$(MAKE) -f CMakeFiles/testdylib.dir/build.make CMakeFiles/testdylib.dir/src/testdylib/libudis86/itab.c.i
.PHONY : src/testdylib/libudis86/itab.c.i

src/testdylib/libudis86/itab.s: src/testdylib/libudis86/itab.c.s
.PHONY : src/testdylib/libudis86/itab.s

# target to generate assembly for a file
src/testdylib/libudis86/itab.c.s:
	$(MAKE) -f CMakeFiles/testdylib.dir/build.make CMakeFiles/testdylib.dir/src/testdylib/libudis86/itab.c.s
.PHONY : src/testdylib/libudis86/itab.c.s

src/testdylib/libudis86/syn-att.o: src/testdylib/libudis86/syn-att.c.o
.PHONY : src/testdylib/libudis86/syn-att.o

# target to build an object file
src/testdylib/libudis86/syn-att.c.o:
	$(MAKE) -f CMakeFiles/testdylib.dir/build.make CMakeFiles/testdylib.dir/src/testdylib/libudis86/syn-att.c.o
.PHONY : src/testdylib/libudis86/syn-att.c.o

src/testdylib/libudis86/syn-att.i: src/testdylib/libudis86/syn-att.c.i
.PHONY : src/testdylib/libudis86/syn-att.i

# target to preprocess a source file
src/testdylib/libudis86/syn-att.c.i:
	$(MAKE) -f CMakeFiles/testdylib.dir/build.make CMakeFiles/testdylib.dir/src/testdylib/libudis86/syn-att.c.i
.PHONY : src/testdylib/libudis86/syn-att.c.i

src/testdylib/libudis86/syn-att.s: src/testdylib/libudis86/syn-att.c.s
.PHONY : src/testdylib/libudis86/syn-att.s

# target to generate assembly for a file
src/testdylib/libudis86/syn-att.c.s:
	$(MAKE) -f CMakeFiles/testdylib.dir/build.make CMakeFiles/testdylib.dir/src/testdylib/libudis86/syn-att.c.s
.PHONY : src/testdylib/libudis86/syn-att.c.s

src/testdylib/libudis86/syn.o: src/testdylib/libudis86/syn.c.o
.PHONY : src/testdylib/libudis86/syn.o

# target to build an object file
src/testdylib/libudis86/syn.c.o:
	$(MAKE) -f CMakeFiles/testdylib.dir/build.make CMakeFiles/testdylib.dir/src/testdylib/libudis86/syn.c.o
.PHONY : src/testdylib/libudis86/syn.c.o

src/testdylib/libudis86/syn.i: src/testdylib/libudis86/syn.c.i
.PHONY : src/testdylib/libudis86/syn.i

# target to preprocess a source file
src/testdylib/libudis86/syn.c.i:
	$(MAKE) -f CMakeFiles/testdylib.dir/build.make CMakeFiles/testdylib.dir/src/testdylib/libudis86/syn.c.i
.PHONY : src/testdylib/libudis86/syn.c.i

src/testdylib/libudis86/syn.s: src/testdylib/libudis86/syn.c.s
.PHONY : src/testdylib/libudis86/syn.s

# target to generate assembly for a file
src/testdylib/libudis86/syn.c.s:
	$(MAKE) -f CMakeFiles/testdylib.dir/build.make CMakeFiles/testdylib.dir/src/testdylib/libudis86/syn.c.s
.PHONY : src/testdylib/libudis86/syn.c.s

src/testdylib/libudis86/udis86.o: src/testdylib/libudis86/udis86.c.o
.PHONY : src/testdylib/libudis86/udis86.o

# target to build an object file
src/testdylib/libudis86/udis86.c.o:
	$(MAKE) -f CMakeFiles/testdylib.dir/build.make CMakeFiles/testdylib.dir/src/testdylib/libudis86/udis86.c.o
.PHONY : src/testdylib/libudis86/udis86.c.o

src/testdylib/libudis86/udis86.i: src/testdylib/libudis86/udis86.c.i
.PHONY : src/testdylib/libudis86/udis86.i

# target to preprocess a source file
src/testdylib/libudis86/udis86.c.i:
	$(MAKE) -f CMakeFiles/testdylib.dir/build.make CMakeFiles/testdylib.dir/src/testdylib/libudis86/udis86.c.i
.PHONY : src/testdylib/libudis86/udis86.c.i

src/testdylib/libudis86/udis86.s: src/testdylib/libudis86/udis86.c.s
.PHONY : src/testdylib/libudis86/udis86.s

# target to generate assembly for a file
src/testdylib/libudis86/udis86.c.s:
	$(MAKE) -f CMakeFiles/testdylib.dir/build.make CMakeFiles/testdylib.dir/src/testdylib/libudis86/udis86.c.s
.PHONY : src/testdylib/libudis86/udis86.c.s

src/testdylib/mach_override.o: src/testdylib/mach_override.c.o
.PHONY : src/testdylib/mach_override.o

# target to build an object file
src/testdylib/mach_override.c.o:
	$(MAKE) -f CMakeFiles/testdylib.dir/build.make CMakeFiles/testdylib.dir/src/testdylib/mach_override.c.o
.PHONY : src/testdylib/mach_override.c.o

src/testdylib/mach_override.i: src/testdylib/mach_override.c.i
.PHONY : src/testdylib/mach_override.i

# target to preprocess a source file
src/testdylib/mach_override.c.i:
	$(MAKE) -f CMakeFiles/testdylib.dir/build.make CMakeFiles/testdylib.dir/src/testdylib/mach_override.c.i
.PHONY : src/testdylib/mach_override.c.i

src/testdylib/mach_override.s: src/testdylib/mach_override.c.s
.PHONY : src/testdylib/mach_override.s

# target to generate assembly for a file
src/testdylib/mach_override.c.s:
	$(MAKE) -f CMakeFiles/testdylib.dir/build.make CMakeFiles/testdylib.dir/src/testdylib/mach_override.c.s
.PHONY : src/testdylib/mach_override.c.s

src/testdylib/main.o: src/testdylib/main.cpp.o
.PHONY : src/testdylib/main.o

# target to build an object file
src/testdylib/main.cpp.o:
	$(MAKE) -f CMakeFiles/testdylib.dir/build.make CMakeFiles/testdylib.dir/src/testdylib/main.cpp.o
.PHONY : src/testdylib/main.cpp.o

src/testdylib/main.i: src/testdylib/main.cpp.i
.PHONY : src/testdylib/main.i

# target to preprocess a source file
src/testdylib/main.cpp.i:
	$(MAKE) -f CMakeFiles/testdylib.dir/build.make CMakeFiles/testdylib.dir/src/testdylib/main.cpp.i
.PHONY : src/testdylib/main.cpp.i

src/testdylib/main.s: src/testdylib/main.cpp.s
.PHONY : src/testdylib/main.s

# target to generate assembly for a file
src/testdylib/main.cpp.s:
	$(MAKE) -f CMakeFiles/testdylib.dir/build.make CMakeFiles/testdylib.dir/src/testdylib/main.cpp.s
.PHONY : src/testdylib/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... bootstrap"
	@echo "... edit_cache"
	@echo "... osxinj"
	@echo "... rebuild_cache"
	@echo "... testapp"
	@echo "... testdylib"
	@echo "... src/bootstrap/main.o"
	@echo "... src/bootstrap/main.i"
	@echo "... src/bootstrap/main.s"
	@echo "... src/osxinj/injector.o"
	@echo "... src/osxinj/injector.i"
	@echo "... src/osxinj/injector.s"
	@echo "... src/osxinj/mach_inject.o"
	@echo "... src/osxinj/mach_inject.i"
	@echo "... src/osxinj/mach_inject.s"
	@echo "... src/osxinj/main.o"
	@echo "... src/osxinj/main.i"
	@echo "... src/osxinj/main.s"
	@echo "... src/testapp/main.o"
	@echo "... src/testapp/main.i"
	@echo "... src/testapp/main.s"
	@echo "... src/testdylib/libudis86/decode.o"
	@echo "... src/testdylib/libudis86/decode.i"
	@echo "... src/testdylib/libudis86/decode.s"
	@echo "... src/testdylib/libudis86/input.o"
	@echo "... src/testdylib/libudis86/input.i"
	@echo "... src/testdylib/libudis86/input.s"
	@echo "... src/testdylib/libudis86/itab.o"
	@echo "... src/testdylib/libudis86/itab.i"
	@echo "... src/testdylib/libudis86/itab.s"
	@echo "... src/testdylib/libudis86/syn-att.o"
	@echo "... src/testdylib/libudis86/syn-att.i"
	@echo "... src/testdylib/libudis86/syn-att.s"
	@echo "... src/testdylib/libudis86/syn.o"
	@echo "... src/testdylib/libudis86/syn.i"
	@echo "... src/testdylib/libudis86/syn.s"
	@echo "... src/testdylib/libudis86/udis86.o"
	@echo "... src/testdylib/libudis86/udis86.i"
	@echo "... src/testdylib/libudis86/udis86.s"
	@echo "... src/testdylib/mach_override.o"
	@echo "... src/testdylib/mach_override.i"
	@echo "... src/testdylib/mach_override.s"
	@echo "... src/testdylib/main.o"
	@echo "... src/testdylib/main.i"
	@echo "... src/testdylib/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

